### ISSUE TITLE
Steam Snap stuck on "Waiting for Network" Screen

### ISSUE THREAD

**Issue by Swift8641** [canonical/steam-snap#254]
**Describe the bug**

**To Reproduce**

1. Download the Steam Snap by Canonical
2. Run the snap 
3. Wait for Updates to finish
4. See error/undesired behavior "aka" Stuck on waiting for network screen.

**Expected behavior**

Steam loads and displays login screen.

**Screenshots**

![Steam Snap Bug Screenshot from 2023-06-15 12-03-47](https://github.com/canonical/steam-snap/assets/111619933/235dddd1-2d93-4f6b-9a27-e3746fa1dc1a)

**Environment**

`snap run steam.report`

```
chase@chase-System-Product-Name:~$ snap run steam report
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
steam.sh[11615]: Running Steam on ubuntu 22.04 64-bit
steam.sh[11615]: STEAM_RUNTIME is enabled automaticallywaiu
setup.sh[11740]: Steam runtime environment up-to-date!
steam.sh[11615]: Steam client's requirements are satisfied

```

**Comment by Swift8641** [comment]
I am connected to the internet and am trying to run the snap package on Ubuntu 22.04.2 LTS with Gnome.

**Comment by Alykar** [comment]
Hi, same issue, and snap reviews are filled with it too.
<details><summary>
snap run steam showed this:</summary>
<p>
`Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
steam.sh[20586]: Running Steam on ubuntu 22.04 64-bit
steam.sh[20586]: STEAM_RUNTIME is enabled automatically
setup.sh[20713]: Steam runtime environment up-to-date!
steam.sh[20586]: Steam client's requirements are satisfied
[2023-06-16 01:11:44] Startup - updater built Jun 14 2023 20:16:17
[2023-06-16 01:11:44] Startup - Steam Client launched with: '/home/alykar/snap/steam/common/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
06/16 01:11:44 Init: Installing breakpad exception handler for appid(steam)/version(1686779606)/tid(20762)
[2023-06-16 01:11:44] Loading cached metrics from disk (/home/alykar/snap/steam/common/.local/share/Steam/package/steam_client_metrics.bin)
[2023-06-16 01:11:44] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-06-16 01:11:44] Using the following download hosts for Public, Realm steamglobal
[2023-06-16 01:11:44] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-06-16 01:11:44] Verifying installation...
[2023-06-16 01:11:44] Verification complete

(process:20762): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
Loaded SDL version 3.0.0-1735-g2e465ae31
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xeae05370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xeae03cc0
GetWin32Stats: display was not open yet, good
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[20814]: Runtime for steamwebhelper: defaulting to /home/alykar/snap/steam/common/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
/home/alykar/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 53: /proc/sys/kernel/unprivileged_userns_clone: Permission denied
/home/alykar/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 60: /proc/sys/user/max_user_namespaces: Permission denied
steamwebhelper.sh[20814]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[20814]: CEF sandbox already disabled
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
flock /sys/power/suspend_stats/success LOCK_SH failed. errno = 13Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Failed to init SteamVR because it isn't installed
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13Warning: failed to set thread priority: set failed for -10: -1: setpriority() failed
Warning: failed to set thread priority: set failed for -10: -1: setpriority() failed
[2023-06-16 01:13:45] Background update loop checking for update. . .
[2023-06-16 01:13:45] Checking for available updates...
[2023-06-16 01:13:45] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12?t=2466171466
[2023-06-16 01:13:45] Manifest download: send request
[2023-06-16 01:13:45] Manifest download: waiting for download to finish
[2023-06-16 01:13:46] Manifest download: finished
[2023-06-16 01:13:46] Download skipped: /client/steam_client_ubuntu12?t=2466171466 version 1686779606, installed version 1686779606, existing pending version 0
[2023-06-16 01:13:46] Nothing to do
`
</p>
</details>

**Comment by Sturmlocke86** [comment]
Same here on Ubuntu 22.04.2 LTS, which I installed freshly a couple of minutes ago.

**Comment by Alykar** [comment]
>How did you get a useful error message? I'm new to Linux.

Just go to console,
You can have 2 versions of steam at the same time.
Snap version (this version) can be started by `snap run steam` and .deb version that can be started by just `steam` command. 

Both will write info while they active, deb will also trigger crash handler that will create .dmp file, if you need it for some reason.

**Comment by Swift8641** [comment]
> >How did you get a useful error message? I'm new to Linux.
> 
> Just go to console,
> You can have 2 versions of steam at the same time.
> Snap version (this version) can be started by `snap run steam` and .deb version that can be started by just `steam` command. 
> 
> Both will write info while they active, deb will also trigger crash handler that will create .dmp file, if you need it for some reason.
> 

Thanks! I'll try that next time I try to get it working.

**Comment by flymike** [comment]
Same here, Ubuntu 22.04 LTS and steam-snap stable/candidate, default Gnome desktop.
See this in CLI output
`Could not connect to X session manager: Could not open network socket`

**Comment by ErneDainesi** [comment]
Having same problem. On ubuntu 20.04

**Comment by Swift8641** [comment]
I was able to get a more useful log dump this time. I've attached it bellow. Hopefully this can help us come of with a solution. 

`chase@chase-System-Product-Name:~$ snap run steam
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
steam.sh[9136]: Running Steam on ubuntu 22.04 64-bit
steam.sh[9136]: STEAM_RUNTIME is enabled automatically
setup.sh[9261]: Steam runtime environment up-to-date!
steam.sh[9136]: Steam client's requirements are satisfied
[2023-06-17 19:24:18] Startup - updater built Jun 16 2023 01:41:16
[2023-06-17 19:24:18] Startup - Steam Client launched with: '/home/chase/snap/steam/common/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
06/17 19:24:18 Init: Installing breakpad exception handler for appid(steam)/version(1686880776)/tid(9307)
[2023-06-17 19:24:18] Loading cached metrics from disk (/home/chase/snap/steam/common/.local/share/Steam/package/steam_client_metrics.bin)
[2023-06-17 19:24:18] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-06-17 19:24:18] Using the following download hosts for Public, Realm steamglobal
[2023-06-17 19:24:18] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-06-17 19:24:18] Verifying installation...
[2023-06-17 19:24:18] Verification complete

(process:9307): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf6aca370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf6ac8cc0
GetWin32Stats: display was not open yet, good
Loaded SDL version 3.0.0-1735-g2e465ae31
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[9428]: Runtime for steamwebhelper: defaulting to /home/chase/snap/steam/common/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
/home/chase/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 53: /proc/sys/kernel/unprivileged_userns_clone: Permission denied
/home/chase/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 60: /proc/sys/user/max_user_namespaces: Permission denied
steamwebhelper.sh[9428]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[9428]: CEF sandbox already disabled
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Failed to init SteamVR because it isn't installed
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13Warning: failed to set thread priority: set failed for -10: -1: setpriority() failed
Warning: failed to set thread priority: set failed for -10: -1: setpriority() failed
[2023-06-17 19:26:18] Background update loop checking for update. . .
[2023-06-17 19:26:18] Checking for available updates...
[2023-06-17 19:26:18] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12?t=2561581491
[2023-06-17 19:26:18] Manifest download: send request
[2023-06-17 19:26:19] Manifest download: waiting for download to finish
[2023-06-17 19:26:19] Manifest download: finished
[2023-06-17 19:26:19] Download skipped: /client/steam_client_ubuntu12?t=2561581491 version 1686880776, installed version 1686880776, existing pending version 0
[2023-06-17 19:26:19] Nothing to do

(steam:9307): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(steam:9307): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
[2023-06-17 19:26:46] Shutdown
`

**Comment by Swift8641** [comment]
It seems like it might be a GTK issue coupled with a failure to open the network socket. To be honest I'm not really sure what to do about it though.

**Comment by selfkonstantin** [comment]
I found a solution to the problem with infinity "Waiting for Network" Screen.
Using snap store (sudo snap install snap-store), go to the section "Installed" and select "Steam" then press button "Permissions" and select all.

**Comment by kenvandine** [comment]
Do you know what connections were connected before when it wasn't working?  And which ones you connected to make it work for you? It should work with the default connections.  Was it failing for any game or specific games?

**Comment by Swift8641** [comment]
I can confirm that enabling all permissions for the snap fixed the issue. The default permissions did not let it work.

**Comment by 240-185** [comment]
> I found a solution to the problem with infinity "Waiting for Network" Screen. Using snap store (sudo snap install snap-store), go to the section "Installed" and select "Steam" then press button "Permissions" and select all.

Thank you!

**Comment by Swift8641** [comment]
After uninstalling and reinstalling the snap it continued to allow all of the connections; not just the default. However, the issue continued. Apparently the fix only works if it was installed with default permissions and then it was allowed full permissions afterwards. Can anyone post what the default permissions are?

**Comment by Swift8641** [comment]
I think these were the defaults. Can anyone else verify? 
![Steam Default Permissions - Screenshot from 2023-06-18 10-35-56](https://github.com/canonical/steam-snap/assets/111619933/3ef001cc-0aad-4fee-881f-4d0fe58b60f6)

**Comment by Swift8641** [comment]
> Do you know what connections were connected before when it wasn't working? And which ones you connected to make it work for you? It should work with the default connections. Was it failing for any game or specific games?

I don't remember exactly what the default permissions were however, I tried to recreate it and posted an image to the thread. It was failing to load at all not just run games. I tried the "fix" however once I logged in refused to load and crashed.

**Comment by Nightmayr** [comment]
I went and tried enabling permissions one at a time to see what manages to get the login window to appear, the answer is `bluez`:

https://github.com/canonical/steam-snap/assets/24817147/fa31d449-b8e9-4a0e-9617-0d1fc312e723

If I disconnect bluez and run steam it will let me log in and get to the main window but on the signing in window it does mention it's "Waiting for the network". In big picture mode if bluez isn't connected you see this:
![Screenshot from 2023-06-18 20-47-12](https://github.com/canonical/steam-snap/assets/24817147/f292a360-bc47-439a-b46f-f5988c48bb61)
![Screenshot from 2023-06-18 20-47-19](https://github.com/canonical/steam-snap/assets/24817147/e80c69c2-08b9-4e85-8fb2-ad5fd00c1100)

**Comment by kenvandine** [comment]
Ah, so it sounds like this only effects big picture mode.  Either way we should request autoconnect for bluez.

**Comment by Nightmayr** [comment]
> Ah, so it sounds like this only effects big picture mode. Either way we should request autoconnect for bluez.

Kinda, it does initially affect desktop/normal mode on new installs by preventing the login window from appearing but yep once successfully signed in the rest of the impact as far as I can tell is just on big picture mode. Agreed on the autoconnect being needed.

**Comment by Swift8641** [comment]
> Seems like enabling "Use Bluetooth devices" permission is enough to make it work.
Enabling the "Use Bluetooth devices" permission allowed me to sign in however the application froze on the "getting user data" screen. The terminal showed this error message.

`(steam:7270): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
`

**Comment by Nightmayr** [comment]
I think judging by the screenshot you sent earlier in this issue of your permissions it looks like you may have accidentally disconnected the `gsettings` interface. By default that's auto-connected at install. I think if you connect that the error should hopefully go away

**Comment by Swift8641** [comment]
> I think judging by the screenshot you sent earlier in this issue of your permissions it looks like you may have accidentally disconnected the `gsettings` interface. By default that's auto-connected at install. If you connect that the error should hopefully go away
> 
> With the default permissions + `bluez` (bluetooth) it should work

Thanks, I reinstalled the snap package and enabled Bluetooth along with the default permissions that reset after I cleared my store cache. I've attached a screenshot of the current settings. It still doesn't work properly but I can login now. 
![Steam Permissions - Screenshot from 2023-06-19 13-42-22](https://github.com/canonical/steam-snap/assets/111619933/0fceb769-92b3-4d81-9920-e0fb4f341a09)

**Comment by ali1234** [comment]
> Ah, so it sounds like this only effects big picture mode. Either way we should request autoconnect for bluez.

Unfortunately big picture is the default mode after installation and there is no obvious way to change to desktop mode if big picture doesn't work. Meaning the snap is currently unusable.

Here is the contents of `snap connections steam` defaults:


```
al@al-desktop:~$ snap connections steam
Interface               Plug                          Slot                                Notes
audio-playback          steam:audio-playback          :audio-playback                     -
audio-record            steam:audio-record            -                                   -
bluez                   steam:bluez                   -                                   -
content[gaming-mesa]    steam:gaming-mesa             gaming-graphics-core22:gaming-mesa  -
content[gtk-3-themes]   steam:gtk-3-themes            gtk-common-themes:gtk-3-themes      -
content[icon-themes]    steam:icon-themes             gtk-common-themes:icon-themes       -
content[sound-themes]   steam:sound-themes            gtk-common-themes:sound-themes      -
desktop                 steam:desktop                 :desktop                            -
desktop-legacy          steam:desktop-legacy          :desktop-legacy                     -
fuse-support            steam:fuse-support            -                                   -
gsettings               steam:gsettings               :gsettings                          -
hardware-observe        steam:hardware-observe        -                                   -
home                    steam:home                    :home                               -
joystick                steam:joystick                :joystick                           -
mount-observe           steam:mount-observe           -                                   -
network                 steam:network                 :network                            -
network-control         steam:network-control         -                                   -
opengl                  steam:opengl                  :opengl                             -
personal-files          steam:dot-local-share-steam   -                                   -
process-control         steam:process-control         -                                   -
removable-media         steam:removable-media         :removable-media                    -
screen-inhibit-control  steam:screen-inhibit-control  :screen-inhibit-control             -
shared-memory           steam:shmem                   :shared-memory                      -
steam-support           steam:steam-support           :steam-support                      -
system-observe          steam:system-observe          -                                   -
uinput                  steam:uinput                  :uinput                             -
upower-observe          steam:upower-observe          :upower-observe                     -
wayland                 steam:wayland                 :wayland                            -
x11                     steam:x11                     :x11                                -
```

After running `snap connect steam:bluez` I was able to log in.

**Comment by Swift8641** [comment]
I've opened a new bug report for anyone else that has issues with steam becoming unresponsive after bypassing the "Waiting for Network" bug. I've attached a link below. The initial post also provides a snapshot of the logs created after applying the workaround of enabling Bluetooth.

https://github.com/canonical/steam-snap/issues/266

**Comment by fakumax** [comment]
Easy to resove.. just unistall STEAM SNAP... and download the original in : https://store.steampowered.com/ ..

install like a package, and works perfectly.

**Comment by Swift8641** [comment]
It seems like the waiting for network bug was fixed on steam's side however steam still refuses to load the store or library.
