### ISSUE TITLE
Add PR_SET_NO_NEW_PRIVS to Steam snapd interface

### ISSUE THREAD

**Issue by ashuntu** [canonical/steam-snap#362]
As noted [here](https://github.com/snapcore/snapd/pull/13489#discussion_r1456440600), we should investigate adding `PR_SET_NO_NEW_PRIVS` to the snapd interface for Steam.

**Comment by smcv** [comment]
The reason I suggested this is that if processes inside the Snap app have the `PR_SET_NO_NEW_PRIVS` flag set (like they do in every Flatpak app), there is no need to worry about whether they can make use of loopholes in the AppArmor profile to gain privileges by executing setuid/setgid/setcap executables, because `PR_SET_NO_NEW_PRIVS` tells the kernel to ignore the setuid/setgid/setcap flag, and instead behave as though it wasn't set.

That means you would not need to be so careful to avoid loopholes in the AppArmor profile, which would hopefully make security review easier.

**Comment by ZoopOTheGoop** [comment]
I'd have to `getcap` to make sure later, but I think there is *something* like this in effect already (unless you've confirmed it doesn't). IIRC I was debugging something (the SteamVR init script IIRC) and it essentially had this behavior because, if I recall correctly, the script calls `pkexec setcap [...]` on a few executables and scripts so it can manage its subprocesses properly. I ended up doing some extensive debugging (removing `pkexec` of course, that was never gonna work) and IIRC concluded that even doing something fairly sophisticated would never allow `setcap` to execute.

Though I understand we are talking about a nightmare scenario and I'm not implying I tested outright escaping confinement altogether. I would support the add regardless because it's at worst idempotent to the current state and at best fixes an attack surface.

**Comment by smcv** [comment]
`setpriv --dump` in the Snap environment says `no_new_privs: 0`.

Having said that, I can't seem to run any of the setuid executables visible in `/usr/bin`, and I don't see any AppArmor denials logged for them either, so there might be something else going on here.

**Comment by smcv** [comment]
(Compare with `setpriv --dump` outputting `no_new_privs: 1` if I copy a `setpriv` executable and its `libcap-ng.so.0` dependency to a location where a Flatpak app can see them.)

**Comment by ZoopOTheGoop** [comment]
this is irrelevant with the upcoming snapd changes AFAIK
