### ISSUE TITLE
Steam's problems with Proton

### ISSUE THREAD

**Issue by valex199132** [canonical/steam-snap#372]
I'm running the latest snap version of Steam (1.0.0.78) and none of my games that need Proton to run work. Some of the games with this problem include Asphalt 9: Legends, Stumble Guys, Disney Speedstorm and Naraka: Bladepoint. No error message is displayed, the games simply won't open. All these same games run normally on Steam in .deb and Flatpak. I'm running Ubuntu 22.04.4 on a Dell Inspiron 5570, Intel Core i5 (8th Gen), Intel® UHD Graphics 620 Tablet, 16 GB, SSD 480 GB.

**Comment by ashuntu** [comment]
Considering the timing and without knowing more, this is likely related to [this](https://github.com/canonical/steam-snap/issues/356) issue.

Can you please run the Steam snap from a terminal with `snap run steam`, run a game, and copy and paste the logs that are displayed in the terminal?

In the future, please use the [Bug Report template](https://github.com/canonical/steam-snap/issues/new?assignees=&labels=type%2Fbug&projects=&template=bug_report.yml&title=%3Ctitle%3E) when opening an issue. It may be worth looking at the linked template and providing the missing information, too.

**Comment by XueSheng-GIT** [comment]
Just installes Ubuntu 24.04 and steam snap. Can't get Proton games to launch.
@valex199132 did you find a solution?

**Comment by valex199132** [comment]
> Just installes Ubuntu 24.04 and steam snap. Can't get Proton games to launch. @valex199132 did you find a solution?

Unfortunately not. I recently installed Ubuntu 24.04 and tried to use Steam in snap again, but the problems with Proton remain the same. I'm using the official Valve version (.deb) and so far I haven't had any problems.

**Comment by Sturmlocke86** [comment]
> > Just installes Ubuntu 24.04 and steam snap. Can't get Proton games to launch. @valex199132 did you find a solution?
> 
> Unfortunately not. I recently installed Ubuntu 24.04 and tried to use Steam in snap again, but the problems with Proton remain the same. I'm using the official Valve version (.deb) and so far I haven't had any problems.

I was having this issue too in Ubuntu 24.04 and what I did to resolve this was to first update snapd. There was an update for this in the snap store, but it wasn't letting me update due to this: https://askubuntu.com/questions/1411104/unable-to-update-snap-store-cannot-refresh-snap-store-snap-snap-store-ha

Then I opened a terminal and typed: `sudo snap refresh snap-store`

The update was installed successfully. After that I rebooted my system. Then I switched the Steam snap channel from stable to bleeding edge and then back to stable and rebooted the machine again. After that most of my games were launching via the Steam snap again. I say "most" because I am unable to launch DC Universe Online, but ten other games launch just fine.
