### ISSUE TITLE
Create desktop shortcut / system application icon doesn't work

### ISSUE THREAD

**Issue by madsrh** [canonical/steam-snap#7]
Checking the checkboxes doesn't actually add a shortcut / icon.

![image](https://user-images.githubusercontent.com/3986894/166121812-932ea66a-add7-46d6-b7cf-3fb2ef8cc98a.png)

**Comment by tommie** [comment]
I just installed Steam through Snap, and was wondering the same thing. I'm on Ubuntu 22.10 using the default GNOME Shell.

The problem is that Steam is sandboxed and writes its `applications/*.desktop` files to `~/snap/steam/common/.local/share/applications/` instead of `~/.local/share/applications/`.

Application menu files are searched for in `$XDG_DATA_DIRS/applications/` (aside from the home location above.)

I created the following file named `~/.config/environment.d/steam-apps.conf`:

```sh
XDG_DATA_DIRS=$HOME/snap/steam/common/.local/share:${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
```

After a logout (and ensuring the systemd user session is actually terminated...) the GNOME Shell lists and launches my games.

This could easily be made into a `systemd.environment-generator` in `/etc/systemd/user-environment-generators/` instead.

---

As for desktop shortcuts, I'm not sure that's as easy: AFAIK there is no environment variable that allows specifying multiple directories to look for desktop icon files. See e.g. `xdg-user-dir DESKTOP`.

* https://specifications.freedesktop.org/menu-spec/latest/ar01s02.html
* https://www.freedesktop.org/software/systemd/man/systemd.environment-generator.html
