### ISSUE TITLE
Blank windows, /proc/sys/user/max_user_namespaces: Permission denied.

### ISSUE THREAD

**Issue by shithedark** [canonical/steam-snap#83]
The steam app suddenly stops displaying screens and running games.

To reproduce : Run steam for hours in the background.

`snap info steam`  
```
name:      steam
summary:   Launcher for the Steam software distribution service (Early Access)
publisher: Canonical✓
store-url: https://snapcraft.io/steam
contact:   https://github.com/canonical/steam-snap
license:   unset
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
commands:
  - steam.report
  - steam
snap-id:      NeoQngJVBf2wKC48bxnF2xqmfEFGdVnx
tracking:     latest/edge
refresh-date: 19 days ago, at 14:28 +03
channels:
  latest/stable:    –                              
  latest/candidate: –                              
  latest/beta:      1.0.0.75 2022-10-07 (52) 365MB -
  latest/edge:      1.0.0.75 2022-11-04 (72) 376MB -
installed:          1.0.0.75            (72) 376MB -
```

`snap version`

```
snap    2.57.5+git1020.gc0cd3ef
snapd   2.57.5+git1020.gc0cd3ef
series  16
ubuntu  22.10
kernel  5.19.0-23-generic
```

Distro & version:  Ubuntu 22.10
CPU:  Intel
GPU:  Intel
GPU Driver Version:  

**Logs**

```
sh: line 60: /proc/sys/user/max_user_namespaces: Permission denied
steamwebhelper.sh[906326]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[906326]: CEF sandbox already disabled
```

**Comment by ZoopOTheGoop** [comment]
The Snap seems to... degrade if you open and close it a bunch, causing this. Changing the channel to another one and back will fix this as a weird workaround. I didn't catch them this time, but there are a bunch of weird AppArmor denials in `proc` and `/usr/lib32` right before this. It seems to almost always be prefaced by a denial for `unprivileged_userns_clone` as well.

It's not entirely clear what it's trying to do, we'd have to figure out when steam tries to call `unprivileged_userns_clone` (which I don't think we can give it access to - that's like one of the top ways to escape sandboxes IIRC). This seems to be a cascade failure where it can't use that and then starts rooting around as a fallback behavior to see if maybe it exceeded the max number of namespaces it can make, and then also trying to read the PID of the subprocess that just got killed. Not sure where `/usr/lib32` gets involved though.

**Comment by ZoopOTheGoop** [comment]
This is interesting

https://github.com/ValveSoftware/steam-runtime/issues/297

It appears to use user namespaces for some of its bubblewrap and runtime functionality, but will fallback to a `setuid` version if it's installed. I wonder if it might be worth staging (setuid) `bubblewrap` instead of letting Steam use its own. Maybe that would remove its attempts to run `unprivileged_userns_clone` while still allowing it to work completely? Still, if bwrap is based on doing this, you'd think Steam's runtimes wouldn't even work on a basic level in the Snap if it's not allowed to make unprivileged user namespaces...

I'm going to need to ask about this (as much a note to self if anything).

**Comment by ZoopOTheGoop** [comment]
I've looked through the `steam_runtime_tools` code and I'm pretty convinced it's already falling back to `setuid` somehow, because it's set up to automatically fail and print a message on how to enable unprivileged namespaces or install `setuid` `bwrap` if it can't acquire the proper tools. So this is probably something else entirely.

**Comment by ashuntu** [comment]
Closing as the original logs shown should not be problematic, and the actual blank window issue should have been resolved. Feel free to reopen if not.
